source 'https://github.com/CocoaPods/Specs.git'

target 'AutoEncodeDecode', :exclusive => true do
  pod "AutoEncodeDecode", :path => "../"
  pod 'ClassProperty', '~> 1.0.0'
end

target 'Tests', :exclusive => true do
  pod "AutoEncodeDecode", :path => "../"

  
end
